default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: megaphone
  password: hunter2
  host: 127.0.0.1

development:
  <<: *default
  database: sales_admin_impl_development

test:
  <<: *default
  database: sales_admin_impl_test
  host: db

production:
  <<: *default
  database: sales_admin_impl_production
  host: db
